experimentName: delta_dense_alif_2
trialConcurrency: 1
maxExperimentDuration: 24h
maxTrialNumber: 100
trainingService:
  platform: local
  useActiveGpu: True
  gpuIndices: 0
searchSpaceFile: ~/lava-dl_exp/nni_experiments/delta_dense_alif_2/search_space/search_space2.json
useAnnotation: false
tuner: 
    name: Anneal
    classArgs:
      optimize_mode: maximize


trialCodeDirectory: ~/lava-dl_exp/nni_experiments/delta_dense_alif_2/code/
trialCommand: python3 experiment1.py --trial_path delta_dense_alif_2/results
experimentWorkingDirectory: ~/lava-dl_exp/nni_experiments/delta_dense_alif_2/results/
trialGpuNumber: 1


